import { StyleSheet } from 'react-native';

export const estilos = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fffefc',
  },
  listPadding: {
    padding: 15,
  },
  screenWithFooter: {
    flex: 1,
  },
  actionFooter: {
    paddingHorizontal: 15,
    paddingTop: 12,
    backgroundColor: '#fffefc',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#d8e3d5',
  },
  horizontalList: {
    marginBottom: 20,
  },
  horizontalListContent: {
    gap: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0f3e17',
    marginBottom: 10,
    marginTop: 10,
  },
  cardHorizontal: {
    backgroundColor: '#e1f4df',
    padding: 12,
    borderRadius: 12,
    width: 108,
    minHeight: 108,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  cardVertical: {
    backgroundColor: '#b1dbb8',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0f3e17',
    marginBottom: 5,
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#222222',
  },
  footerButtons: {
    marginTop: 20,
    gap: 10,
  },
  buttonPressed: {
    opacity: 0.75,
  },
  primaryButton: {
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  addPetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
  },
  addTurnButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
  },
  petModalRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  petModalBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(18, 32, 22, 0.55)',
  },
  petPhotoCard: {
    width: '100%',
    maxWidth: '90%',
    backgroundColor: '#fffefc',
    borderRadius: 12,
    padding: 16,
    margin: 24,
  },
  petPhotoClose: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 1,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fffefc',
    borderRadius: 20,
  },
  petPhoto: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 8,
    marginBottom: 14,
    backgroundColor: '#e1f4df',
  },
  buttonTextPrimary: {
    color: '#fffefc',
    fontWeight: 'bold',
    fontSize: 16,
  },
  profileOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#cfe7d3',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  profileOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileOptionText: {
    fontSize: 16,
    marginLeft: 15,
    color: '#222222',
    fontWeight: '500',
  },
  profileOptionTextHighlight: {
    color: '#0c2f10',
  },
  profileHeader: {
    backgroundColor: '#0f3e17',
    padding: 18,
    borderRadius: 12,
    marginBottom: 18,
  },
  profileHeaderNombre: {
    color: '#fffefc',
    fontSize: 20,
    fontWeight: 'bold',
  },
  profileHeaderEmail: {
    color: '#cfe7d3',
    fontSize: 14,
    marginTop: 4,
  },
  modalCard: {
    width: '100%',
    maxWidth: '90%',
    backgroundColor: '#fffefc',
    borderRadius: 12,
    padding: 20,
    margin: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0f3e17',
    marginBottom: 10,
  },
  modalText: {
    fontSize: 15,
    color: '#333333',
    lineHeight: 22,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalButtonNeutral: {
    backgroundColor: '#e1f4df',
  },
  modalButtonPrimary: {
    backgroundColor: '#0f3e17',
  },
  modalButtonText: {
    fontWeight: 'bold',
    fontSize: 15,
  },
  modalButtonTextDark: {
    color: '#0f3e17',
  },
  modalButtonTextLight: {
    color: '#fffefc',
  },
  formTitle: {
    color: '#0f3e17',
    fontSize: 28,
    fontWeight: 'bold',
  },
  formSubtitle: {
    color: '#555d54',
    fontSize: 15,
    marginTop: 8,
    marginBottom: 26,
  },
  formLabel: {
    color: '#263b32',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 8,
  },
  formInput: {
    width: '100%',
    backgroundColor: '#f3f7f1',
    borderColor: '#d8e3d5',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontSize: 16,
  },
  formInputUltimo: {
    marginBottom: 20,
  },
  formWrapper: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    minHeight: 44,
  },
  backText: {
    color: '#0f3e17',
    fontSize: 16,
    fontWeight: '600',
  },
  formContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: '#0f3e17',
    borderRadius: 10,
    padding: 16,
    marginTop: 6,
  },
  submitText: {
    color: '#fffefc',
    fontSize: 16,
    fontWeight: 'bold',
  },
  historialCard: {
    backgroundColor: '#b1dbb8',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  historialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  historialFecha: {
    fontSize: 13,
    color: '#263b32',
    fontWeight: '600',
  },
  qrBoton: {
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginVertical: 12,
  },
  qrBotonFila: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  escanerContenedor: {
    flex: 1,
    backgroundColor: '#fffefc',
    paddingHorizontal: 20,
  },
  escanerCamara: {
    flex: 1,
    backgroundColor: '#12281e',
    borderRadius: 12,
    overflow: 'hidden',
  },
  escanerBarraSuperior: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  escanerVolver: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: '#fffefc',
  },
  escanerVolverTexto: {
    color: '#263b32',
    fontSize: 16,
    fontWeight: '600',
  },
  escanerCerrar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fffefc',
  },
  escanerMarco: {
    position: 'absolute',
    top: '18%',
    left: '16%',
    width: '68%',
    aspectRatio: 1,
    borderWidth: 3,
    borderColor: '#fffefc',
    borderRadius: 16,
  },
  escanerPie: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
    backgroundColor: 'rgba(18, 40, 30, 0.92)',
  },
  escanerInstruccion: {
    color: '#fffefc',
    fontSize: 15,
    textAlign: 'center',
  },
  escanerResultado: {
    alignItems: 'center',
    gap: 10,
  },
  escanerResultadoLabel: {
    color: '#cfe7d3',
    fontSize: 13,
    fontWeight: '600',
  },
  escanerResultadoTexto: {
    color: '#fffefc',
    fontSize: 16,
    textAlign: 'center',
  },
  escanerMensaje: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 24,
  },
  escanerMensajeTitulo: {
    color: '#0f3e17',
    fontSize: 28,
    fontWeight: 'bold',
  },
  escanerMensajeTexto: {
    color: '#333333',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
});