import { StyleSheet } from 'react-native';

export const estilos = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fffefc',
  },
  listPadding: {
    padding: 15,
  },
  screenWithFooter: {
    flex: 1,
  },
  actionFooter: {
    paddingHorizontal: 15,
    paddingTop: 12,
    backgroundColor: '#fffefc',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#d8e3d5',
  },
  horizontalList: {
    marginBottom: 20,
  },
  horizontalListContent: {
    gap: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0f3e17',
    marginBottom: 10,
    marginTop: 10,
  },
  cardHorizontal: {
    backgroundColor: '#e1f4df',
    padding: 12,
    borderRadius: 12,
    width: 108,
    minHeight: 108,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  cardVertical: {
    backgroundColor: '#b1dbb8',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0f3e17',
    marginBottom: 5,
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#222222',
  },
  footerButtons: {
    marginTop: 20,
    gap: 10,
  },
  buttonPressed: {
    opacity: 0.75,
  },
  primaryButton: {
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  addPetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
  },
  addTurnButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#0f3e17',
    padding: 15,
    borderRadius: 10,
  },
  petModalRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  petModalBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(18, 32, 22, 0.55)',
  },
  petPhotoCard: {
    width: '100%',
    maxWidth: '90%',
    backgroundColor: '#fffefc',
    borderRadius: 12,
    padding: 16,
  },
  petPhotoClose: {
    position: 'absolute',
    top: 24,
    right: 24,
    zIndex: 1,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fffefc',
    borderRadius: 20,
  },
  petPhoto: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 8,
    marginBottom: 14,
    backgroundColor: '#e1f4df',
  },
  buttonTextPrimary: {
    color: '#fffefc',
    fontWeight: 'bold',
    fontSize: 16,
  },
  profileOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#cfe7d3',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderColor: '#efeeeb',
    borderWidth: 1,
  },
  profileOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileOptionText: {
    fontSize: 16,
    marginLeft: 15,
    color: '#222222',
    fontWeight: '500',
  },
  profileOptionTextHighlight: {
    color: '#0c2f10',
  },
});